head() ::= <<
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>$constants.defaultTitle$</title>
    <link type="text/css" rel="stylesheet" href="$constants.cssBase$/normalize.css"/>
    <link type="text/css" rel="stylesheet" href="$constants.cssBase$/foundation.min.css"/>
    <link type="text/css" rel="stylesheet" href="$constants.cssBase$/foundation-icons/foundation-icons.css"/>
    <link type="text/css" rel="stylesheet" href='$constants.mgBase$/css/metricsgraphics.css'/>
    <link type="text/css" rel="stylesheet" href="$constants.cssBase$/custom.css"/>

    <script type="application/javascript" src="$constants.jsBase$/vendor/modernizr.js"></script>
    <script type="application/javascript" src="$constants.jsBase$/vendor/jquery.js"></script>
    <script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.11/d3.min.js" charset="utf-8"></script>
    <script type="application/javascript" src="$constants.mgBase$/js/metricsgraphics.js"></script>
    <script type="application/javascript" src="$constants.jsBase$/foundation.min.js"></script>
    <script type="application/javascript" src="$constants.jsBase$/moment.min.js"></script>
    <script type="application/javascript" src="$constants.jsBase$/moment-timezone.min.js"></script>
    <script type="application/javascript" src="$constants.jsBase$/custom.js"></script>
</head>
>>